In [ ]:
import pandas as pd
import numpy as np
import datetime



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Cascade Cup /train.csv")

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/Cascade Cup /test.csv")

In [ ]:
df.head()

order_time  order_id  ... session_time cancelled_time
0  2021-01-26 02:21:35    556753  ...          NaN            NaN
1  2021-01-26 02:33:16    556754  ...     3.266667            NaN
2  2021-01-26 02:39:49    556755  ...     9.816667            NaN
3  2021-01-26 02:47:53    556756  ...    17.533333            NaN
4  2021-01-26 03:06:30    556757  ...     1.350000            NaN

[5 rows x 20 columns]

In [ ]:
df.dtypes

order_time               object
order_id                  int64
order_date               object
allot_time               object
accept_time              object
pickup_time              object
delivered_time           object
rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
cancelled                 int64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method      object
reassignment_reason      object
reassigned_order        float64
session_time            float64
cancelled_time           object
dtype: object

In [ ]:
df[["order_time","order_date", "allot_time", "accept_time","pickup_time","delivered_time","cancelled_time"]] = df[["order_time","order_date", "allot_time", "accept_time","pickup_time","delivered_time","cancelled_time"]].apply(pd.to_datetime)

In [ ]:
df2.dtypes

order_time               object
order_id                  int64
order_date               object
allot_time               object
accept_time              object
rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method      object
reassignment_reason      object
reassigned_order        float64
session_time            float64
dtype: object

In [ ]:
df2[["order_time","order_date", "allot_time", "accept_time"]] = df2[["order_time","order_date", "allot_time","accept_time"]].apply(pd.to_datetime)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df2.dtypes

order_time              datetime64[ns]
order_id                         int64
order_date              datetime64[ns]
allot_time              datetime64[ns]
accept_time             datetime64[ns]
rider_id                         int64
first_mile_distance            float64
last_mile_distance             float64
alloted_orders                 float64
delivered_orders               float64
undelivered_orders             float64
lifetime_order_count           float64
reassignment_method             object
reassignment_reason             object
reassigned_order               float64
session_time                   float64
dtype: object

In [ ]:
df.head()

order_time  order_id  ... session_time cancelled_time
0 2021-01-26 02:21:35    556753  ...          NaN            NaT
1 2021-01-26 02:33:16    556754  ...     3.266667            NaT
2 2021-01-26 02:39:49    556755  ...     9.816667            NaT
3 2021-01-26 02:47:53    556756  ...    17.533333            NaT
4 2021-01-26 03:06:30    556757  ...     1.350000            NaT

[5 rows x 20 columns]

In [ ]:
N_rows = df.shape[0]

In [ ]:
N_rows2 = df2.shape[0]

In [ ]:
N_rows2

144844

In [ ]:
df["Week_day"] = 0


In [ ]:
df2["Week_day"] = 0

In [ ]:
df["Week_day"] = df["order_date"].dt.weekday

In [ ]:
df2["Week_day"] = df2["order_date"].dt.weekday



In [ ]:
df.head()

order_time  order_id  ... cancelled_time Week_day
0 2021-01-26 02:21:35    556753  ...            NaT        1
1 2021-01-26 02:33:16    556754  ...            NaT        1
2 2021-01-26 02:39:49    556755  ...            NaT        1
3 2021-01-26 02:47:53    556756  ...            NaT        1
4 2021-01-26 03:06:30    556757  ...            NaT        1

[5 rows x 21 columns]

In [ ]:
df["Week_day"].unique()

array([1, 2, 3, 4, 5, 6, 0])

In [ ]:
duplicate = df[df.duplicated()]
  
duplicate

order_time  order_id  ...      cancelled_time Week_day
420456 2021-02-05 15:06:30    181402  ... 2021-02-05 16:59:52        4

[1 rows x 21 columns]

In [ ]:
 df.drop_duplicates(inplace = True)

In [ ]:
duplicate = df2[df2.duplicated()]
  
duplicate

Empty DataFrame
Columns: [order_time, order_id, order_date, allot_time, accept_time, rider_id, first_mile_distance, last_mile_distance, alloted_orders, delivered_orders, undelivered_orders, lifetime_order_count, reassignment_method, reassignment_reason, reassigned_order, session_time, Week_day]
Index: []

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 449999 entries, 0 to 449999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype         
---  ------                --------------   -----         
 0   order_time            449999 non-null  datetime64[ns]
 1   order_id              449999 non-null  int64         
 2   order_date            449999 non-null  datetime64[ns]
 3   allot_time            449999 non-null  datetime64[ns]
 4   accept_time           449842 non-null  datetime64[ns]
 5   pickup_time           447579 non-null  datetime64[ns]
 6   delivered_time        444782 non-null  datetime64[ns]
 7   rider_id              449999 non-null  int64         
 8   first_mile_distance   449999 non-null  float64       
 9   last_mile_distance    449999 non-null  float64       
 10  alloted_orders        433051 non-null  float64       
 11  delivered_orders      432658 non-null  float64       
 12  cancelled             449999 non-null  int64         
 13 

In [ ]:
N_rows = df.shape[0]

In [ ]:
N_rows

449999

In [ ]:
from datetime import datetime, date

In [ ]:
df["accept_time"][56].time()

datetime.time(3, 48, 37)

In [ ]:
df["accept_time"][1].minute

34

In [ ]:
df.isnull().sum()

order_time                   0
order_id                     0
order_date                   0
allot_time                   0
accept_time                157
pickup_time               2420
delivered_time            5217
rider_id                     0
first_mile_distance          0
last_mile_distance           0
alloted_orders           16948
delivered_orders         17341
cancelled                    0
undelivered_orders       17341
lifetime_order_count        53
reassignment_method     436256
reassignment_reason     436247
reassigned_order        436247
session_time              3675
cancelled_time          444782
Week_day                     0
dtype: int64

In [ ]:
df = df.dropna(subset=['accept_time'], how='any')
df.shape

(449842, 21)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.isnull().sum()

order_time                   0
order_id                     0
order_date                   0
allot_time                   0
accept_time                  0
pickup_time               2263
delivered_time            5060
rider_id                     0
first_mile_distance          0
last_mile_distance           0
alloted_orders           16932
delivered_orders         17323
cancelled                    0
undelivered_orders       17323
lifetime_order_count        50
reassignment_method     436108
reassignment_reason     436100
reassigned_order        436100
session_time              3672
cancelled_time          444782
Week_day                     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 449842 entries, 0 to 449999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype         
---  ------                --------------   -----         
 0   order_time            449842 non-null  datetime64[ns]
 1   order_id              449842 non-null  int64         
 2   order_date            449842 non-null  datetime64[ns]
 3   allot_time            449842 non-null  datetime64[ns]
 4   accept_time           449842 non-null  datetime64[ns]
 5   pickup_time           447579 non-null  datetime64[ns]
 6   delivered_time        444782 non-null  datetime64[ns]
 7   rider_id              449842 non-null  int64         
 8   first_mile_distance   449842 non-null  float64       
 9   last_mile_distance    449842 non-null  float64       
 10  alloted_orders        432910 non-null  float64       
 11  delivered_orders      432519 non-null  float64       
 12  cancelled             449842 non-null  int64         
 13 

In [ ]:
N_rows = df.shape[0]

In [ ]:
df.head()

order_time  order_id  ... cancelled_time Week_day
0 2021-01-26 02:21:35    556753  ...            NaT        1
1 2021-01-26 02:33:16    556754  ...            NaT        1
2 2021-01-26 02:39:49    556755  ...            NaT        1
3 2021-01-26 02:47:53    556756  ...            NaT        1
4 2021-01-26 03:06:30    556757  ...            NaT        1

[5 rows x 21 columns]

In [ ]:
df["order_time"] = df["order_time"].dt.hour*60 + df["order_time"].dt.minute
df["allot_time"] = df["allot_time"].dt.hour*60 + df["allot_time"].dt.minute
df["pickup_time"] = df["pickup_time"].dt.hour*60 + df["pickup_time"].dt.minute
df["delivered_time"] = df["delivered_time"].dt.hour*60 + df["delivered_time"].dt.minute


In [ ]:
df2.dtypes

order_time              datetime64[ns]
order_id                         int64
order_date              datetime64[ns]
allot_time              datetime64[ns]
accept_time             datetime64[ns]
rider_id                         int64
first_mile_distance            float64
last_mile_distance             float64
alloted_orders                 float64
delivered_orders               float64
undelivered_orders             float64
lifetime_order_count           float64
reassignment_method             object
reassignment_reason             object
reassigned_order               float64
session_time                   float64
Week_day                         int64
dtype: object

In [ ]:
df2["order_time"] = df2["order_time"].dt.hour*60 + df2["order_time"].dt.minute
df2["allot_time"] = df2["allot_time"].dt.hour*60 + df2["allot_time"].dt.minute


In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.head()

order_time  order_id order_date  ...  session_time cancelled_time  Week_day
0         141    556753 2021-01-26  ...           NaN            NaT         1
1         153    556754 2021-01-26  ...      3.266667            NaT         1
2         159    556755 2021-01-26  ...      9.816667            NaT         1
3         167    556756 2021-01-26  ...     17.533333            NaT         1
4         186    556757 2021-01-26  ...      1.350000            NaT         1

[5 rows x 21 columns]

In [ ]:
df.drop(['order_id','cancelled_time'], axis = 1, inplace = True)
 

In [ ]:
df3 = df2["order_id"]
df2.drop(['order_id' ], axis = 1, inplace = True)
 

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.dtypes

order_time                       int64
order_date              datetime64[ns]
allot_time                       int64
accept_time             datetime64[ns]
pickup_time                    float64
delivered_time                 float64
rider_id                         int64
first_mile_distance            float64
last_mile_distance             float64
alloted_orders                 float64
delivered_orders               float64
cancelled                        int64
undelivered_orders             float64
lifetime_order_count           float64
reassignment_method             object
reassignment_reason             object
reassigned_order               float64
session_time                   float64
Week_day                         int64
dtype: object

In [ ]:
df["month"] = df["order_date"].dt.month
df["date"]= df["order_date"].dt.day

In [ ]:
df2["month"] = df2["order_date"].dt.month
df2["date"]= df2["order_date"].dt.day

In [ ]:
 df["accept_time"] = df["accept_time"].dt.hour*60 + df["accept_time"].dt.minute
 
 

In [ ]:
 df2["accept_time"] = df2["accept_time"].dt.hour*60 + df2["accept_time"].dt.minute
 
 

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.dtypes

order_time                       int64
order_date              datetime64[ns]
allot_time                       int64
accept_time                      int64
pickup_time                    float64
delivered_time                 float64
rider_id                         int64
first_mile_distance            float64
last_mile_distance             float64
alloted_orders                 float64
delivered_orders               float64
cancelled                        int64
undelivered_orders             float64
lifetime_order_count           float64
reassignment_method             object
reassignment_reason             object
reassigned_order               float64
session_time                   float64
Week_day                         int64
month                            int64
date                             int64
dtype: object

In [ ]:
 df.head()

order_time order_date  allot_time  ...  Week_day  month  date
0         141 2021-01-26         141  ...         1      1    26
1         153 2021-01-26         153  ...         1      1    26
2         159 2021-01-26         159  ...         1      1    26
3         167 2021-01-26         168  ...         1      1    26
4         186 2021-01-26         187  ...         1      1    26

[5 rows x 21 columns]

In [ ]:
df.drop(['order_date'], axis = 1, inplace = True)


In [ ]:
df2.drop(['order_date'], axis = 1, inplace = True)


In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.head()

order_time  allot_time  accept_time  ...  Week_day  month  date
0         141         141          142  ...         1      1    26
1         153         153          154  ...         1      1    26
2         159         159          160  ...         1      1    26
3         167         168          169  ...         1      1    26
4         186         187          187  ...         1      1    26

[5 rows x 20 columns]

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['reassignment_reason']= le.fit_transform(df['reassignment_reason'])

In [ ]:
df2['reassignment_reason']= le.fit_transform(df2['reassignment_reason'])
df2['reassignment_method']= le.fit_transform(df2['reassignment_method'])
df2['reassigned_order']= le.fit_transform(df2['reassigned_order'])

In [ ]:
df['reassignment_method']= le.fit_transform(df['reassignment_method'])

In [ ]:
df['reassigned_order']= le.fit_transform(df['reassigned_order'])

In [ ]:
df['reassigned_order'].unique()

array([1, 0])

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.describe()

order_time     allot_time  ...         month           date
count  449842.000000  449842.000000  ...  449842.00000  449842.000000
mean      794.010301     795.215040  ...       1.47570      16.468367
std       216.618319     216.674944  ...       0.49941      12.738485
min        44.000000      44.000000  ...       1.00000       1.000000
25%       558.000000     559.000000  ...       1.00000       3.000000
50%       866.000000     867.000000  ...       1.00000      26.000000
75%       966.000000     968.000000  ...       2.00000      29.000000
max      1301.000000    1301.000000  ...       2.00000      31.000000

[8 rows x 20 columns]

In [ ]:
df.isnull().sum()

order_time                  0
allot_time                  0
accept_time                 0
pickup_time              2263
delivered_time           5060
rider_id                    0
first_mile_distance         0
last_mile_distance          0
alloted_orders          16932
delivered_orders        17323
cancelled                   0
undelivered_orders      17323
lifetime_order_count       50
reassignment_method         0
reassignment_reason         0
reassigned_order            0
session_time             3672
Week_day                    0
month                       0
date                        0
dtype: int64

In [ ]:
df2.isnull().sum()

order_time                 0
allot_time                 0
accept_time               68
rider_id                   0
first_mile_distance        0
last_mile_distance         0
alloted_orders          4773
delivered_orders        4884
undelivered_orders      4884
lifetime_order_count     778
reassignment_method        0
reassignment_reason        0
reassigned_order           0
session_time            5054
Week_day                   0
month                      0
date                       0
dtype: int64

In [ ]:
df = df.dropna(subset=['pickup_time','session_time'], how='any')
df.shape

(443987, 20)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 443987 entries, 1 to 449999
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   order_time            443987 non-null  int64  
 1   allot_time            443987 non-null  int64  
 2   accept_time           443987 non-null  int64  
 3   pickup_time           443987 non-null  float64
 4   delivered_time        441251 non-null  float64
 5   rider_id              443987 non-null  int64  
 6   first_mile_distance   443987 non-null  float64
 7   last_mile_distance    443987 non-null  float64
 8   alloted_orders        427540 non-null  float64
 9   delivered_orders      427191 non-null  float64
 10  cancelled             443987 non-null  int64  
 11  undelivered_orders    427191 non-null  float64
 12  lifetime_order_count  443950 non-null  float64
 13  reassignment_method   443987 non-null  int64  
 14  reassignment_reason   443987 non-null  int64  
 15  

In [ ]:
df1 = df

In [ ]:
df21 = df2

In [ ]:
df.isnull().sum()

order_time                  0
allot_time                  0
accept_time                 0
pickup_time                 0
delivered_time           2736
rider_id                    0
first_mile_distance         0
last_mile_distance          0
alloted_orders          16447
delivered_orders        16796
cancelled                   0
undelivered_orders      16796
lifetime_order_count       37
reassignment_method         0
reassignment_reason         0
reassigned_order            0
session_time                0
Week_day                    0
month                       0
date                        0
dtype: int64

In [ ]:
df['alloted_orders'].fillna(0, inplace = True)

In [ ]:
df2['alloted_orders'].fillna(0, inplace = True)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df1['alloted_orders'].fillna(df1['alloted_orders'].mean(), inplace = True)

In [ ]:
df21['alloted_orders'].fillna(df21['alloted_orders'].mean(), inplace = True)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df2.isnull().sum()

order_time                 0
allot_time                 0
accept_time               68
rider_id                   0
first_mile_distance        0
last_mile_distance         0
alloted_orders             0
delivered_orders        4884
undelivered_orders      4884
lifetime_order_count     778
reassignment_method        0
reassignment_reason        0
reassigned_order           0
session_time            5054
Week_day                   0
month                      0
date                       0
dtype: int64

In [ ]:
df1['delivered_orders'].fillna(df1['delivered_orders'].mean(), inplace = True)
df['delivered_orders'].fillna(0, inplace = True)

In [ ]:
df21['delivered_orders'].fillna(df21['delivered_orders'].mean(), inplace = True)
df2['delivered_orders'].fillna(0, inplace = True)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.isnull().sum()

order_time                  0
allot_time                  0
accept_time                 0
pickup_time                 0
delivered_time           2736
rider_id                    0
first_mile_distance         0
last_mile_distance          0
alloted_orders              0
delivered_orders            0
cancelled                   0
undelivered_orders      16796
lifetime_order_count       37
reassignment_method         0
reassignment_reason         0
reassigned_order            0
session_time                0
Week_day                    0
month                       0
date                        0
dtype: int64

In [ ]:
df1['undelivered_orders'].fillna(df1['undelivered_orders'].mean(), inplace = True)
df['undelivered_orders'].fillna(0, inplace = True)

In [ ]:
df21['undelivered_orders'].fillna(df21['undelivered_orders'].mean(), inplace = True)
df2['undelivered_orders'].fillna(0, inplace = True)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df = df.dropna(subset=['lifetime_order_count'], how='any')
df.shape

(443950, 20)

In [ ]:
df1 = df1.dropna(subset=['lifetime_order_count'], how='any')
df.shape

(443950, 20)

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df2.isnull().sum()

order_time                 0
allot_time                 0
accept_time               68
rider_id                   0
first_mile_distance        0
last_mile_distance         0
alloted_orders             0
delivered_orders           0
undelivered_orders         0
lifetime_order_count     778
reassignment_method        0
reassignment_reason        0
reassigned_order           0
session_time            5054
Week_day                   0
month                      0
date                       0
dtype: int64

In [ ]:
df21.isnull().sum()

order_time                 0
allot_time                 0
accept_time               68
rider_id                   0
first_mile_distance        0
last_mile_distance         0
alloted_orders             0
delivered_orders           0
undelivered_orders         0
lifetime_order_count     778
reassignment_method        0
reassignment_reason        0
reassigned_order           0
session_time            5054
Week_day                   0
month                      0
date                       0
dtype: int64

In [ ]:
df.head()

order_time  allot_time  accept_time  ...  Week_day  month  date
1         153         153          154  ...         1      1    26
2         159         159          160  ...         1      1    26
3         167         168          169  ...         1      1    26
4         186         187          187  ...         1      1    26
7         194         194          194  ...         1      1    26

[5 rows x 20 columns]

In [ ]:
df["order_allot"] = df["allot_time"] - df["order_time"] 
df["allot_accept"] = -df["allot_time"] + df["accept_time"] 
df["accept_pickup"] = df["pickup_time"] - df["accept_time"] 
df["pickup_deliver"] = df["delivered_time"] - df["pickup_time"] 
 
 
 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [ ]:
df1["order_allot"] = df1["allot_time"] - df1["order_time"] 
df1["allot_accept"] = -df1["allot_time"] + df1["accept_time"] 
df1["accept_pickup"] = df1["pickup_time"] - df1["accept_time"] 
df1["pickup_deliver"] = df1["delivered_time"] - df1["pickup_time"] 
 
 
 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [ ]:
df2.dtypes

order_time                int64
allot_time                int64
accept_time             float64
rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method       int64
reassignment_reason       int64
reassigned_order          int64
session_time            float64
Week_day                  int64
month                     int64
date                      int64
dtype: object

In [ ]:
df2["order_allot"] = df2["allot_time"] - df2["order_time"] 
df2["allot_accept"] = -df2["allot_time"] + df2["accept_time"] 
 
 
 
 

In [ ]:
df21["order_allot"] = df21["allot_time"] - df21["order_time"] 
df21["allot_accept"] = -df21["allot_time"] + df21["accept_time"] 
 
 
 
 


In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.drop(['order_time', 	'allot_time',	'accept_time',	'pickup_time'	, 'delivered_time'], axis = 1, inplace = True)


In [ ]:
df1.drop(['order_time', 	'allot_time',	'accept_time',	'pickup_time'	, 'delivered_time'], axis = 1, inplace = True)


In [ ]:
df2.drop(['order_time', 	'allot_time',	'accept_time' ], axis = 1, inplace = True)


In [ ]:
df21.dtypes

rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method       int64
reassignment_reason       int64
reassigned_order          int64
session_time            float64
Week_day                  int64
month                     int64
date                      int64
order_allot               int64
allot_accept            float64
dtype: object

In [ ]:
# df21.drop(['order_time', 	'allot_time',	'accept_time' ], axis = 1, inplace = True


In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df.head()

rider_id  first_mile_distance  ...  accept_pickup  pickup_deliver
1     18117             2.520700  ...           16.0            21.0
2     18623             2.207400  ...           16.0            16.0
3     15945             2.189400  ...           32.0            20.0
4     17589             2.787000  ...           24.0            29.0
7      8493             0.025681  ...           19.0             9.0

[5 rows x 19 columns]

In [ ]:
df2.head()

rider_id  first_mile_distance  ...  order_allot  allot_accept
0     12884               1.6585  ...            0           1.0
1      3541               2.0709  ...            0           0.0
2       603               1.3884  ...            1           1.0
3      3414               1.9039  ...            0           0.0
4      1426               0.8275  ...            0           1.0

[5 rows x 16 columns]

In [ ]:
df["undelivered_orders"].unique()

array([0.        , 1.        , 3.        , 2.        , 0.76558963,
       4.        , 6.        , 5.        , 7.        , 9.        ,
       8.        ])

In [ ]:
column_maxes = df.max()

In [ ]:
column_maxes

rider_id                21566.000000
first_mile_distance        42.038100
last_mile_distance         22.410000
alloted_orders            567.000000
delivered_orders          562.000000
cancelled                   1.000000
undelivered_orders          9.000000
lifetime_order_count    30469.000000
reassignment_method         2.000000
reassignment_reason         3.000000
reassigned_order            1.000000
session_time             1298.966667
Week_day                    6.000000
month                       2.000000
date                       31.000000
order_allot               128.000000
allot_accept               16.000000
accept_pickup             252.000000
pickup_deliver            637.000000
dtype: float64

In [ ]:
df.dtypes

rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
cancelled                 int64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method       int64
reassignment_reason       int64
reassigned_order          int64
session_time            float64
Week_day                  int64
month                     int64
date                      int64
order_allot               int64
allot_accept              int64
accept_pickup           float64
pickup_deliver          float64
dtype: object

In [ ]:
df['session_time'].unique()

array([  3.26666667,   9.81666667,  17.53333333, ..., 381.28333333,
       220.03333333, 278.75      ])

In [ ]:
df['first_mile_distance'] = (df['first_mile_distance']/df['first_mile_distance'].max())*100

In [ ]:
df1['first_mile_distance'] = (df1['first_mile_distance']/df1['first_mile_distance'].max())*100
df1['last_mile_distance'] = (df1['last_mile_distance']/df1['last_mile_distance'].max())*100
df1['alloted_orders'] = (df1['alloted_orders']/df1['alloted_orders'].max())*100
df1['delivered_orders'] = (df1['delivered_orders']/df1['delivered_orders'].max())*100
df1['undelivered_orders'] = (df1['undelivered_orders']/df1['undelivered_orders'].max())*100
df1['lifetime_order_count'] = (df1['lifetime_order_count']/df1['lifetime_order_count'].max())*100
df1['session_time'] = (df1['session_time']/df1['session_time'].max())*100
df1['order_allot'] = (df1['order_allot']/df1['order_allot'].max())*100
df1['allot_accept'] = (df1['allot_accept']/df1['allot_accept'].max())*100
df1['accept_pickup'] = (df1['accept_pickup']/df1['accept_pickup'].max())*100
df1['pickup_deliver'] = (df1['pickup_deliver']/df1['pickup_deliver'].max())*100




In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
df['first_mile_distance']

1         5.996227
2         5.250951
3         5.208133
4         6.629700
7         0.061091
            ...   
449995    1.377084
449996    4.724999
449997    3.792750
449998    6.883993
449999    4.501869
Name: first_mile_distance, Length: 443950, dtype: float64

In [ ]:
df.dtypes

rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
cancelled                 int64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method       int64
reassignment_reason       int64
reassigned_order          int64
session_time            float64
Week_day                  int64
month                     int64
date                      int64
order_allot               int64
allot_accept              int64
accept_pickup           float64
pickup_deliver          float64
dtype: object

In [ ]:
df['last_mile_distance'] = (df['last_mile_distance']/df['last_mile_distance'].max())*100
df['alloted_orders'] = (df['alloted_orders']/df['alloted_orders'].max())*100
df['delivered_orders'] = (df['delivered_orders']/df['delivered_orders'].max())*100
df['undelivered_orders'] = (df['undelivered_orders']/df['undelivered_orders'].max())*100
df['lifetime_order_count'] = (df['lifetime_order_count']/df['lifetime_order_count'].max())*100
df['session_time'] = (df['session_time']/df['session_time'].max())*100
df['order_allot'] = (df['order_allot']/df['order_allot'].max())*100
df['allot_accept'] = (df['allot_accept']/df['allot_accept'].max())*100
df['accept_pickup'] = (df['accept_pickup']/df['accept_pickup'].max())*100
df['pickup_deliver'] = (df['pickup_deliver']/df['pickup_deliver'].max())*100


In [ ]:
df21['first_mile_distance'] = (df21['first_mile_distance']/df21['first_mile_distance'].max())*100
df21['last_mile_distance'] = (df21['last_mile_distance']/df21['last_mile_distance'].max())*100
df21['alloted_orders'] = (df21['alloted_orders']/df21['alloted_orders'].max())*100
df21['delivered_orders'] = (df21['delivered_orders']/df21['delivered_orders'].max())*100
df21['undelivered_orders'] = (df21['undelivered_orders']/df21['undelivered_orders'].max())*100
df21['lifetime_order_count'] = (df21['lifetime_order_count']/df21['lifetime_order_count'].max())*100
df21['session_time'] = (df21['session_time']/df21['session_time'].max())*100
df21['order_allot'] = (df21['order_allot']/df21['order_allot'].max())*100
df21['allot_accept'] = (df21['allot_accept']/df21['allot_accept'].max())*100





In [ ]:
df.head()


rider_id  first_mile_distance  ...  accept_pickup  pickup_deliver
1     18117             5.996227  ...       6.349206        3.296703
2     18623             5.250951  ...       6.349206        2.511774
3     15945             5.208133  ...      12.698413        3.139717
4     17589             6.629700  ...       9.523810        4.552590
7      8493             0.061091  ...       7.539683        1.412873

[5 rows x 19 columns]

In [ ]:
df['pickup_deliver'].fillna(0, inplace = True)

In [ ]:
df1['pickup_deliver'].fillna(0, inplace = True)

In [ ]:
Y = df['cancelled']

In [ ]:
Y1 = df1['cancelled']

In [ ]:
df['cancelled'].unique()

array([0, 1])

In [ ]:
Y.unique()

array([0, 1])

In [ ]:
 
X = df.drop(['pickup_deliver','cancelled','accept_pickup'], axis = 1)

In [ ]:
 
X1 = df1.drop(['pickup_deliver','cancelled','accept_pickup'], axis = 1)

In [ ]:
X.shape

(443950, 16)

In [ ]:
df['accept_pickup'].unique()

array([   6.34920635,   12.6984127 ,    9.52380952,    7.53968254,
         17.85714286,    5.95238095,    3.17460317,    1.19047619,
          8.73015873,    3.96825397,    3.57142857,    2.38095238,
          9.92063492,    4.36507937,    7.93650794,    5.15873016,
         10.71428571,   14.28571429,   11.11111111,   11.50793651,
          1.98412698,    6.74603175,    7.14285714,    5.55555556,
         11.9047619 ,   10.31746032,    8.33333333,    9.12698413,
          1.58730159,    2.77777778,    4.76190476,   13.88888889,
         12.3015873 ,   20.23809524,   13.49206349,   16.26984127,
         14.68253968,   37.3015873 ,   15.07936508,   22.61904762,
         15.47619048,   13.0952381 ,   17.06349206,   26.58730159,
         20.63492063,   15.87301587,   18.65079365,   18.25396825,
          0.3968254 ,    0.79365079,   25.79365079,   23.01587302,
         25.3968254 ,   16.66666667,   35.31746032,   23.41269841,
         17.46031746,   19.44444444,   28.17460317,   19.84126

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.2, random_state=0)

In [ ]:
#import classifier algorithm here
from sklearn.linear_model import LogisticRegression

# create classifier
lg_model = LogisticRegression()

#Training the classifier
lg_model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
X.shape

(443950, 16)

In [ ]:
X.dtypes

rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method       int64
reassignment_reason       int64
reassigned_order          int64
session_time            float64
Week_day                  int64
month                     int64
date                      int64
order_allot             float64
allot_accept            float64
dtype: object

In [ ]:
df2.dtypes

rider_id                  int64
first_mile_distance     float64
last_mile_distance      float64
alloted_orders          float64
delivered_orders        float64
undelivered_orders      float64
lifetime_order_count    float64
reassignment_method       int64
reassignment_reason       int64
reassigned_order          int64
session_time            float64
Week_day                  int64
month                     int64
date                      int64
order_allot             float64
allot_accept            float64
dtype: object

In [ ]:
lg_model.fit(X,Y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
np.any(np.isnan(X_train))


False

In [ ]:
np.all(np.isfinite(X_train))


True

In [ ]:
X_train = X_train.reset_index()


In [ ]:
X_train.isnull().values.any()

False

In [ ]:
X_train.isnull().sum().sum()

0

In [ ]:
check_nan_in_df = X_train.isnull().sum()
print(check_nan_in_df)

index                   0
rider_id                0
first_mile_distance     0
last_mile_distance      0
alloted_orders          0
delivered_orders        0
undelivered_orders      0
lifetime_order_count    0
reassignment_method     0
reassignment_reason     0
reassigned_order        0
session_time            0
Week_day                0
month                   0
date                    0
order_allot             0
allot_accept            0
dtype: int64


In [ ]:
X_train.isnull().sum()

index                   0
rider_id                0
first_mile_distance     0
last_mile_distance      0
alloted_orders          0
delivered_orders        0
undelivered_orders      0
lifetime_order_count    0
reassignment_method     0
reassignment_reason     0
reassigned_order        0
session_time            0
Week_day                0
month                   0
date                    0
order_allot             0
allot_accept            0
dtype: int64

In [ ]:
# import evaluation metrics
from sklearn.metrics import confusion_matrix, accuracy_score

# evaluate the model
y_pred = lg_model.predict(X_test)

# Get the accuracy
print("Accuracy Score of Logistic Regression classifier: ","{:.4f}".format(accuracy_score(y_test, y_pred)))

Accuracy Score of Logistic Regression classifier:  0.9939


In [ ]:
df2.isnull().sum()

rider_id                   0
first_mile_distance        0
last_mile_distance         0
alloted_orders             0
delivered_orders           0
undelivered_orders         0
lifetime_order_count     778
reassignment_method        0
reassignment_reason        0
reassigned_order           0
session_time            5054
Week_day                   0
month                      0
date                       0
order_allot                0
allot_accept              68
dtype: int64

In [ ]:
df2['lifetime_order_count'].fillna(0, inplace = True)

In [ ]:

df2['session_time'].fillna(0, inplace = True)
df2['allot_accept'].fillna(0, inplace = True)

In [ ]:
y_pred = lg_model.predict(df2)

In [ ]:
ans = pd.DataFrame(y_pred, columns = ['Cancelled'])

In [ ]:
ans['Cancelled'].unique()

array([0, 1])

In [ ]:
ans['Cancelled'].shape

(144844,)

In [ ]:
df2.shape

(144844, 16)

In [ ]:
 df3 = pd.read_csv("/content/drive/MyDrive/Cascade Cup /test.csv")

In [ ]:
df3.shape 

(144844, 16)

In [ ]:
ans['order_id'] = df3['order_id']

In [ ]:
ans.head()

Cancelled  order_id
0          0    130231
1          0    130232
2          0    130233
3          0    130234
4          0    130235

In [ ]:
columns_titles = ["order_id","Cancelled"]
ans=ans.reindex(columns=columns_titles)

In [ ]:
ans.head()

order_id  Cancelled
0    130231          0
1    130232          0
2    130233          0
3    130234          0
4    130235          0

In [ ]:
ans.to_csv('file_name.csv', index=False)


In [ ]:
# #Import Random Forest Model
# from sklearn.ensemble import RandomForestClassifier

# #Create a Gaussian Classifier
# clf=RandomForestClassifier(n_estimators=200)

# #Train the model using the training sets y_pred=clf.predict(X_test)
# clf.fit(X,Y)

# y_pred=clf.predict(df2)

In [ ]:
ans1 = pd.DataFrame(y_pred, columns = ['cancelled'])

In [ ]:
ans1['order_id'] = df3['order_id']

In [ ]:
columns_titles = ["order_id","cancelled"]
ans1=ans1.reindex(columns=columns_titles)

In [ ]:
ans1.to_csv('RF_200.csv', index=False)


In [ ]:
#Import Random Forest Model
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X ,Y)

#Predict the response for test dataset
y_pred = clf.predict(df2)

 

In [ ]:
ans2 = pd.DataFrame(y_pred, columns = ['cancelled'])
ans2['order_id'] = df3['order_id']
columns_titles = ["order_id","cancelled"]
ans2=ans2.reindex(columns=columns_titles)
ans2.to_csv('Decision_Tree_100.csv', index=False)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=7)

#Train the model using the training sets
knn.fit(X, Y)

#Predict the response for test dataset
y_pred = knn.predict(df2)

KeyboardInterrupt: ignored

In [ ]:
ans4 = pd.DataFrame(y_pred, columns = ['cancelled'])
ans4['order_id'] = df3['order_id']
columns_titles = ["order_id","cancelled"]
ans4=ans4.reindex(columns=columns_titles)
ans4.to_csv('KNN.csv', index=False)


In [ ]:
#Import Random Forest Model
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

clf = DecisionTreeClassifier(max_depth = 49)

# Train Decision Tree Classifer
clf = clf.fit(X1 ,Y1)

#Predict the response for test dataset
y_pred = clf.predict(df21)

 

In [ ]:
ans2 = pd.DataFrame(y_pred, columns = ['cancelled'])
ans2['order_id'] = df3['order_id']
columns_titles = ["order_id","cancelled"]
ans2=ans2.reindex(columns=columns_titles)
ans2.to_csv('Decision_Tree_100_3.csv', index=False)
